//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnactus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalles_pedidos
    {
        public int Id { get; set; }
        public int id_pedido { get; set; }
        public int id_producto { get; set; }
        public int cantidad { get; set; }
    
        public virtual pedidos pedidos { get; set; }
        public virtual productos productos { get; set; }
    }
}
